language: python
python:
  - "3.7"
  - "3.8"
os: windows
before_install:
  - pip install -U pip
  - pip install -U pytest
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest ./Tests -m "not long"
