matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3 --version=3.7
        - choco feature enable -n allowGlobalConfirmation
        - choco install femm
        - choco install vcredist-all
      install:
        - py -m pip install -r requirements.txt
      # command to run tests
      script:
        - py -m pytest ./Tests -m "not long"
