language: python
python:
  - "3.7"
  - "3.8"
os: windows
before_install:
  - pip3 install -U pip
  - pip3 install -U pytest
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - python3 -m pytest ./Tests -m "not long"
