matrix:
  include:
    - os: windows
      language: sh
      python: 
        - "3.7"
        - "3.8"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      install:
        - pip install -r requirements.txt
      # command to run tests
      script:
        - python -m pytest ./Tests -m "not long"
